demonstration_configs:
- domain_randomization:
    cameras:
      config_path: configs/cameras/fixed_camera_lift2_simbox.yml
      type: fixed
    random_environment:
      has_wall: false
      hdr: false
      robot_base_position: false
      robot_eepose: false
      table_texture: false
      table_type: false
      wall_texture: false
      random_visuals:
      - prim_path: /World/_scene/obj_table/model_9938e4a048e8362cb22105425b506d4a_0/Looks/_512fb5f7ae59d0001df77ef/Num613e3bde3e8f6d0001279e90
        type: mdl
        assets_pattern: miscs/mdl/ebench/mdl/table/train/.*\.mdl$
      - prim_path: /World/_scene/obj_table/model_9938e4a048e8362cb22105425b506d4a_0/Looks/_512fb5f80db560001884c36/Num613e3bde3e8f6d0001279e90
        type: mdl
        assets_pattern: miscs/mdl/ebench/mdl/table/train/.*\.mdl$
      - prim_path: /World/_scene/obj_dish1/Looks/material0/baseColorTex
        type: texture
        assets_pattern: scene_usds/ebench/long_horizon/scene_dish/textures/dish1_texture/train/.*\.png$
      - prim_path: /World/_scene/obj_dish2/Looks/material0/baseColorTex
        type: texture
        assets_pattern: scene_usds/ebench/long_horizon/scene_dish/textures/dish2_texture/train/.*\.png$
      - prim_path: /World/_scene/obj_dish3/Looks/material0/baseColorTex
        type: texture
        assets_pattern: scene_usds/ebench/long_horizon/scene_dish/textures/dish3_texture/train/.*\.png$
      - prim_path: /World/_scene/obj_glass/Looks/material0/baseColorTex
        type: texture
        assets_pattern: scene_usds/ebench/long_horizon/scene_dish/textures/glass_texture/train/.*\.png$
    rewrite_instruction: false
  generation_config:
    action_path:
      mode: manual
      actions:
      - type: move_to
        move_type: alignv2
        rel_object_uid: dish3
        arm: left
        delta_position:
          x: null
          y: 0.0
          yaw: null
      - type: custom_motion
        motion_list:
          left:
          - name: left
            translation:
            - 0.0
            - 0.2
            - 0.12
            orientation:
            - 0.40557978767263886
            - 0.5792279653395692
            - -0.40557978767263886
            - -0.5792279653395692
            grasp: false
            rel_object_uid: dish3
            type: object_frame
          - name: left
            translation:
            - 0.0
            - 0.15
            - 0.12
            orientation:
            - 0.40557978767263886
            - 0.5792279653395692
            - -0.40557978767263886
            - -0.5792279653395692
            grasp: false
            rel_object_uid: dish3
            type: object_frame
          - name: left
            translation:
            - 0.0
            - 0.3
            - 0.12
            orientation:
            - 0.40557978767263886
            - 0.5792279653395692
            - -0.40557978767263886
            - -0.5792279653395692
            grasp: true
            rel_object_uid: dish3
            type: object_frame
      - type: move_to
        move_type: alignv2
        rel_object_uid: basket_big
        arm: left
        grasp: true
        delta_position:
          x: null
          y: 0.0
          yaw: null
      - type: custom_motion
        motion_list:
          left:
          - name: left
            translation:
            - 0.0
            - 0.27
            - 0.12
            orientation:
            - 0.40557978767263886
            - 0.5792279653395692
            - -0.40557978767263886
            - -0.5792279653395692
            grasp: true
            rel_object_uid: basket_big
            type: object_frame
          - name: left
            translation:
            - 0.0
            - 0.15
            - 0.12
            orientation:
            - 0.40557978767263886
            - 0.5792279653395692
            - -0.40557978767263886
            - -0.5792279653395692
            grasp: true
            rel_object_uid: basket_big
            type: object_frame
          - name: left
            translation:
            - 0.0
            - 0.15
            - 0.12
            orientation:
            - 0.40557978767263886
            - 0.5792279653395692
            - -0.40557978767263886
            - -0.5792279653395692
            grasp: false
            rel_object_uid: basket_big
            type: object_frame
          - name: left
            cnt: 50
            grasp: false
            type: reset
      - type: move_to
        move_type: alignv2
        rel_object_uid: dish1
        arm: left
        delta_position:
          x: null
          y: 0.0
          yaw: null
      - type: custom_motion
        motion_list:
          left:
          - name: left
            translation:
            - 0.0
            - 0.2
            - 0.1
            orientation:
            - 0.40557978767263886
            - 0.5792279653395692
            - -0.40557978767263886
            - -0.5792279653395692
            grasp: false
            rel_object_uid: dish1
            type: object_frame
          - name: left
            translation:
            - 0.0
            - 0.15
            - 0.1
            orientation:
            - 0.40557978767263886
            - 0.5792279653395692
            - -0.40557978767263886
            - -0.5792279653395692
            grasp: false
            rel_object_uid: dish1
            type: object_frame
          - name: left
            translation:
            - 0.0
            - 0.3
            - 0.1
            orientation:
            - 0.40557978767263886
            - 0.5792279653395692
            - -0.40557978767263886
            - -0.5792279653395692
            grasp: true
            rel_object_uid: dish1
            type: object_frame
      - type: move_to
        move_type: alignv2
        rel_object_uid: basket_big
        arm: left
        grasp: true
        delta_position:
          x: null
          y: 0.0
          yaw: null
      - type: custom_motion
        motion_list:
          left:
          - name: left
            translation:
            - 0.0
            - 0.27
            - 0.1
            orientation:
            - 0.40557978767263886
            - 0.5792279653395692
            - -0.40557978767263886
            - -0.5792279653395692
            grasp: true
            rel_object_uid: basket_big
            type: object_frame
          - name: left
            translation:
            - 0.0
            - 0.18
            - 0.1
            orientation:
            - 0.40557978767263886
            - 0.5792279653395692
            - -0.40557978767263886
            - -0.5792279653395692
            grasp: true
            rel_object_uid: basket_big
            type: object_frame
          - name: left
            translation:
            - 0.0
            - 0.18
            - 0.1
            orientation:
            - 0.40557978767263886
            - 0.5792279653395692
            - -0.40557978767263886
            - -0.5792279653395692
            grasp: false
            rel_object_uid: basket_big
            type: object_frame
          - name: left
            cnt: 50
            grasp: false
            type: reset
      - type: move_to
        move_type: alignv2
        rel_object_uid: dish2
        arm: left
        delta_position:
          x: null
          y: 0.0
          yaw: null
      - type: custom_motion
        motion_list:
          left:
          - name: left
            translation:
            - 0.0
            - 0.2
            - 0.1
            orientation:
            - 0.40557978767263886
            - 0.5792279653395692
            - -0.40557978767263886
            - -0.5792279653395692
            grasp: false
            rel_object_uid: dish2
            type: object_frame
          - name: left
            translation:
            - 0.0
            - 0.15
            - 0.1
            orientation:
            - 0.40557978767263886
            - 0.5792279653395692
            - -0.40557978767263886
            - -0.5792279653395692
            grasp: false
            rel_object_uid: dish2
            type: object_frame
          - name: left
            translation:
            - 0.0
            - 0.3
            - 0.1
            orientation:
            - 0.40557978767263886
            - 0.5792279653395692
            - -0.40557978767263886
            - -0.5792279653395692
            grasp: true
            rel_object_uid: dish2
            type: object_frame
      - type: move_to
        move_type: alignv2
        rel_object_uid: basket_big
        arm: left
        grasp: true
        delta_position:
          x: null
          y: 0.0
          yaw: null
      - type: custom_motion
        motion_list:
          left:
          - name: left
            translation:
            - 0.0
            - 0.27
            - 0.1
            orientation:
            - 0.40557978767263886
            - 0.5792279653395692
            - -0.40557978767263886
            - -0.5792279653395692
            grasp: true
            rel_object_uid: basket_big
            type: object_frame
          - name: left
            translation:
            - 0.0
            - 0.19
            - 0.1
            orientation:
            - 0.40557978767263886
            - 0.5792279653395692
            - -0.40557978767263886
            - -0.5792279653395692
            grasp: true
            rel_object_uid: basket_big
            type: object_frame
          - name: left
            translation:
            - 0.0
            - 0.19
            - 0.1
            orientation:
            - 0.40557978767263886
            - 0.5792279653395692
            - -0.40557978767263886
            - -0.5792279653395692
            grasp: false
            rel_object_uid: basket_big
            type: object_frame
          - name: left
            cnt: 50
            grasp: false
            type: reset
      - type: move_to
        move_type: alignv2
        rel_object_uid: glass
        arm: left
        delta_position:
          x: null
          y: 0.0
          yaw: null
      - type: custom_motion
        motion_list:
          left:
          - name: left
            translation:
            - 0.05
            - 0.23
            - 0.05
            orientation:
            - -0.09229595564125714
            - -0.560985526796931
            - 0.7010573846499779
            - 0.43045933457687946
            grasp: false
            rel_object_uid: glass
            type: object_frame
          - name: left
            translation:
            - 0.05
            - 0.16
            - 0.05
            orientation:
            - -0.09229595564125714
            - -0.560985526796931
            - 0.7010573846499779
            - 0.43045933457687946
            grasp: false
            rel_object_uid: glass
            type: object_frame
          - name: left
            translation:
            - 0.05
            - 0.28
            - 0.05
            orientation:
            - -0.09229595564125714
            - -0.560985526796931
            - 0.7010573846499779
            - 0.43045933457687946
            grasp: true
            rel_object_uid: glass
            type: object_frame
      - type: move_to
        move_type: alignv2
        rel_object_uid: basket_big
        arm: left
        grasp: true
        delta_position:
          x: null
          y: 0.0
          yaw: null
      - type: custom_motion
        motion_list:
          left:
          - name: left
            translation:
            - 0.05
            - 0.27
            - 0.05
            orientation:
            - -0.09229595564125714
            - -0.560985526796931
            - 0.7010573846499779
            - 0.43045933457687946
            grasp: true
            rel_object_uid: basket_big
            type: object_frame
          - name: left
            translation:
            - 0.05
            - 0.22
            - 0.05
            orientation:
            - -0.09229595564125714
            - -0.560985526796931
            - 0.7010573846499779
            - 0.43045933457687946
            grasp: true
            rel_object_uid: basket_big
            type: object_frame
          - name: left
            translation:
            - 0.05
            - 0.22
            - 0.05
            orientation:
            - -0.09229595564125714
            - -0.560985526796931
            - 0.7010573846499779
            - 0.43045933457687946
            grasp: false
            rel_object_uid: basket_big
            type: object_frame
          - name: left
            cnt: 50
            grasp: false
            type: reset
      - type: move_to
        move_type: dalignv2
        rel_object_uid: spoon
        arm: right
        delta_position:
          x: null
          y: 0.0
          yaw: null
      - type: custom_motion
        motion_list:
          right:
          - name: right
            translation:
            - 0.0
            - 0.2
            - 0.025
            orientation:
            - 0.70711
            - 0.0
            - 0.0
            - -0.70711
            grasp: false
            rel_object_uid: spoon
            type: object_frame
          - name: right
            translation:
            - 0.0
            - 0.155
            - 0.025
            orientation:
            - 0.70711
            - 0.0
            - 0.0
            - -0.70711
            grasp: false
            rel_object_uid: spoon
            type: object_frame
          - name: right
            translation:
            - 0.0
            - 0.155
            - 0.025
            orientation:
            - 0.70711
            - 0.0
            - 0.0
            - -0.70711
            grasp: true
            rel_object_uid: spoon
            type: object_frame
          - name: right
            translation:
            - 0.0
            - 0.3
            - 0.025
            orientation:
            - 0.6532814824381883
            - -0.2705980500730985
            - -0.2705980500730985
            - -0.6532814824381883
            grasp: true
            rel_object_uid: spoon
            type: object_frame
      - type: move_to
        move_type: alignv2
        rel_object_uid: basket_small
        arm: right
        grasp: true
        delta_position:
          x: null
          y: 0.0
          yaw: null
      - type: custom_motion
        motion_list:
          right:
          - name: right
            translation:
            - 0.07
            - 0.2
            - 0.0
            orientation:
            - 0.3535533905932738
            - 0.3535533905932738
            - -0.6123724356957945
            - -0.6123724356957945
            grasp: true
            rel_object_uid: basket_small
            type: object_frame
          - name: right
            translation:
            - 0.07
            - 0.2
            - 0.0
            orientation:
            - 0.3535533905932738
            - 0.3535533905932738
            - -0.6123724356957945
            - -0.6123724356957945
            grasp: false
            rel_object_uid: basket_small
            type: object_frame
          - name: right
            cnt: 50
            grasp: false
            type: reset
      robot: 0
    articulation: []
    goal:
    - - obj1_uid:
        - dish1
        obj2_uid:
        - basket_big
        position:
        - top
      - obj1_uid:
        - dish2
        obj2_uid:
        - basket_big
        position:
        - top
      - obj1_uid:
        - dish3
        obj2_uid:
        - basket_big
        position:
        - top
      - obj1_uid:
        - glass
        obj2_uid:
        - basket_big
        position:
        - top
      - obj1_uid:
        - spoon
        obj2_uid:
        - basket_small
        position:
        - top
    mode: manual
    planner: curobo
  instruction: Put all the dishes into the big basket and the spoon into the small
    basket.
  layout_config:
    ignored_objects: []
    type: random_custom_tableset
    custom_tableset:
    - dish1:
        w: 0.1
        h: 0.1
        angle: 0
        angle_bilateral: false
        type: centric_range
        buffer_size: 0.02
      dish2:
        w: 0.1
        h: 0.1
        angle: 0
        angle_bilateral: false
        type: centric_range
        buffer_size: 0.03
      dish3:
        w: 0.1
        h: 0.1
        angle: 0
        angle_bilateral: false
        type: centric_range
        buffer_size: 0.03
      glass:
        w: 0.1
        h: 0.1
        angle: 0
        angle_bilateral: false
        type: centric_range
        buffer_size: 0.03
      spoon:
        w: 0.1
        h: 0.1
        angle: 0
        angle_bilateral: false
        type: centric_range
      basket_big:
        w: 0.1
        h: 0.1
        angle: 0
        angle_bilateral: false
        type: centric_range
      basket_small:
        w: 0.1
        h: 0.1
        angle: 0
        angle_bilateral: false
        type: centric_range
  mode: manual
  num_episode: 250
  object_config:
    dish1:
      type: existed_object
      uid_list:
      - dish1
      is_not_rigid: true
      without_colliders: true
    dish2:
      type: existed_object
      uid_list:
      - dish2
      is_not_rigid: true
      without_colliders: true
    dish3:
      type: existed_object
      uid_list:
      - dish3
      is_not_rigid: true
      without_colliders: true
    glass:
      type: existed_object
      uid_list:
      - glass
      is_not_rigid: true
      without_colliders: true
    spoon:
      type: existed_object
      uid_list:
      - spoon
      is_not_rigid: true
      without_colliders: true
    basket_big:
      type: existed_object
      uid_list:
      - basket_big
      is_not_rigid: true
      without_colliders: true
    basket_small:
      type: existed_object
      uid_list:
      - basket_small
      is_not_rigid: true
      without_colliders: true
  preprocess_config: []
  robots:
  - type: manip/lift2/R5a
    position:
    - 0.75
    - 0.0
    - -0.65
    orientation:
    - 0.0
    - 0.0
    - 0.0
    - 1.0
  table_uid: table
  task_name: ebench/mobile_manip/dish_test_mini
  usd_name: scene_usds/ebench/long_horizon/scene_dish/scene
  env_vars:
    MDL_SYSTEM_PATH: "/isaac-sim/materials/:{ASSETS_DIR}/miscs/mdl/ebench/mdl:{ASSETS_DIR}/scene_usds/ebench/simple_pnp/task3/SubUSDs/materials"
evaluation_configs:
- domain_randomization:
    cameras:
      config_path: configs/cameras/fixed_camera_lift2_simbox.yml
      type: fixed
  num_test: 20
  num_steps: 5000
  robots:
  - type: manip/lift2/R5a
    position:
    - 0.85
    - 0.0
    - -0.65
    orientation:
    - 0.0
    - 0.0
    - 0.0
    - 1.0
  table_uid: table
  task_name: ebench/mobile_manip/dish_test_mini
  usd_name: scene_usds/ebench/long_horizon/scene_dish/scene
  env_vars:
    MDL_SYSTEM_PATH: "/isaac-sim/materials/:{ASSETS_DIR}/miscs/mdl/ebench/mdl:{ASSETS_DIR}/scene_usds/ebench/simple_pnp/task3/SubUSDs/materials"
