demonstration_configs:
- domain_randomization: &id001
    cameras:
      config_path: configs/cameras/fixed_camera_lift2_simbox.yml
      type: fixed
    random_environment:
      has_wall: false
      hdr: false
      robot_base_position: false
      robot_eepose: false
      table_texture: false
      table_type: false
      wall_texture: false
    rewrite_instruction: false
  generation_config: &id002
    action_path:
      mode: auto
      robot: 0
    articulation: []
    goal: [[]]
    mode: manual
    planner: curobo
  instruction: no instruction
  layout_config: &id003
    ignored_objects: []
    type: None
  mode: manual
  num_episode: 2
  object_config: {}
  preprocess_config: []
  robots:
  - &id006
    type: manip/lift2/R5a
    position: [0, 0, 0]
  table_uid: table
  task_name: ebench/table_top_manip/put_glass_in_glassbox
  usd_name: scene_usds/ebench/teleop_tasks/put_glass_in_glassbox/scene
  env_vars:
    MDL_SYSTEM_PATH: "/isaac-sim/materials/:{ASSETS_DIR}/miscs/mdl/ebench/mdl"
evaluation_configs:
- domain_randomization: *id001
  generation_config: *id002
  instruction: no instruction
  layout_config: *id003
  mode: manual
  num_test: 12
  num_steps: 3000
  physics_dt: 0.0166666667
  rendering_dt: 0.0166666667
  object_config:
    glass:
      type: existed_object
      is_articulated: true
      target_positions: null
      uid_list:
      - glass
    glassbox:
      type: existed_object
      is_articulated: true
      target_positions: null
      uid_list:
      - glassbox
  physics_scene_config:
    BounceThreshold: 0.0
    BroadphaseType: GPU
    CollisionSystem: PCM
    EnableCCD: false
    EnableEnhancedDeterminism: false
    EnableExternalForcesEveryIteration: false
    EnableGPUDynamics: false
    EnableResidualReporting: false
    EnableSceneQuerySupport: true
    EnableStabilization: false
    FrictionCorrelationDistance: 0.02500000037252903
    FrictionOffsetThreshold: 0.03999999910593033
    FrictionType: patch
    GpuCollisionStackSize: 67108864
    GpuFoundLostAggregatePairsCapacity: 1024
    GpuFoundLostPairsCapacity: 262144
    GpuHeapCapacity: 67108864
    GpuMaxDeformableSurfaceContacts: 1048576
    GpuMaxHairContacts: 1048576
    GpuMaxNumPartitions: 8
    GpuMaxParticleContacts: 1048576
    GpuMaxRigidContactCount: 524288
    GpuMaxRigidPatchCount: 81920
    GpuMaxSoftBodyContacts: 1048576
    GpuTempBufferCapacity: 16777216
    GpuTotalAggregatePairsCapacity: 1024
    InvertCollisionGroupFilter: false
    MaxBiasCoefficient: Inf
    MaxPositionIterationCount: 255
    MaxVelocityIterationCount: 255
    MinPositionIterationCount: 1
    MinVelocityIterationCount: 0
    ReportKinematicKinematicPairs: false
    ReportKinematicStaticPairs: false
    SolverType: PGS
    TimeStepsPerSecond: 60
    UpdateType: Synchronous
  preprocess_config:
  - config:
      Restitution: 0.0
      DynamicFriction: 0.5
      StaticFriction: 0.5
      FrictionCombineMode: max
      RestitutionCombineMode: multiply
      ImprovePatchFriction: true
    robot_type: lift2
    type: set_robot_physics_material
  robots:
  - *id006
  table_uid: table
  task_name: ebench/table_top_manip/put_glass_in_glassbox_val_train_20p
  usd_name: scene_usds/ebench/teleop_tasks/put_glass_in_glassbox/scene
  env_vars:
    MDL_SYSTEM_PATH: "/isaac-sim/materials/:{ASSETS_DIR}/miscs/mdl/ebench/mdl"
