demonstration_configs:
- domain_randomization:
    cameras:
      config_path: configs/cameras/fixed_camera_robotiq_s2r_3L_align_twoObs.yml
      type: fixed
    object_data_path: obj_container
    random_environment:
      has_wall: true
      hdr: true
      robot_base_position:
        random_range: 0.05
      robot_eepose: false
      table_texture: true
      table_type: true
      wall_texture: true
    rewrite_instruction: true
  generation_config:
    reset_tcp: true
    action_path:
      mode: auto
      robot: 0
    articulation: []
    goal:
    - - obj1_uid:
        - obj1_0
        obj2_uid:
        - obj2
        position:
        - top
        fixed_position: true
        allow_fixed_grasp: true
        force_fixed_grasp: true
    mode: random_all
    planner: curobo
  instruction: ''
  layout_config:
    ignored_objects: []
    type: random_custom_tableset
    in_order: true
    custom_tableset:
      obj1_0: &id001
        random_range_angle: 360
        random_range_h: 0.7
        random_range_w: 0.4
        random_range_x: -0.2
        random_range_y: -0.35
        type: global_range
      obj2: *id001
      background_0: &id002
        random_range_angle: 360
        random_range_h: 20
        random_range_w: 20
        random_range_x: -10
        random_range_y: -10
        type: global_range
      background_1: *id002
      background_2: *id002
      background_3: *id002
      background_4: *id002
      background_5: *id002
      background_6: *id002
      background_7: *id002
      background_8: *id002
  mode: manual
  num_episode: 1000000
  restart_per_success: 100
  object_config:
    background_0: &id003
      filter_rule: []
      max_cached_num: 30
      fixed_scale: 1.0
      option:
      - plain_replace
      path: object_usds/real2sim_usd/background
      type: load_object_from_path
    background_1: *id003
    background_2: *id003
    background_3: *id003
    background_4: *id003
    background_5: *id003
    background_6: *id003
    background_7: *id003
    background_8: *id003
    obj1_0:
      filter_rule: []
      max_cached_num: 30
      fixed_scale: 1.0
      option:
      - plain_replace
      path: object_usds/real2sim_usd/Object
      type: load_object_from_path
    obj2:
      filter_rule: []
      max_cached_num: 30
      fixed_scale: 1.0
      option:
      - force_top
      - plain_replace
      path: object_usds/real2sim_usd/Container
      type: load_object_from_path
  preprocess_config:
  - config:
      type: ccd
    type: ccd
  - config:
      config: default
      type: convexDecomposition
    type: collider
  robots:
  - config:
      gripper_type: robotiq
    default_joint_positions:
    - 0.0
    - -0.785
    - 0.0
    - -2.356
    - 0.0
    - 1.57079
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    type: franka
  table_uid: aa49db8a801d402dac6cf1579536502c
  task_name: system1_scaling_real2sim2real_object_fgrandpos_bgrandpos_fgclip_NOrobotbaserandpos_bgcache10_bgclip_3L2obsAlign_refineActionSpace_refineGraspPose
  usd_name: scene_usds/sim2real_scenes_align_for_scaling/base
evaluation_configs: []
