demonstration_configs:
- domain_randomization:
    cameras:
      config_path: configs/cameras/fixed_camera_aloha_refined.yml
      type: fixed
    object_data_path: objaverse_annotation_refined_pnp
    random_environment:
      has_wall: true
      hdr: true
      robot_base_position:
        random_range: 0.05
      robot_eepose: false
      table_texture: true
      table_type: true
      wall_texture: true
    rewrite_instruction: true
  generation_config:
    reset_tcp: true
    action_path:
      mode: auto
      robot: 0
    articulation: []
    goal:
    - - obj1_uid:
        - obj1_0
        obj2_uid:
        - obj2
        position:
        - top
        fixed_position: true
        arm: auto
    mode: random_all
    planner: curobo
  instruction: ''
  layout_config:
    ignored_objects: []
    type: random_custom_tableset
    in_order: true
    custom_tableset:
      obj1_0: &id001
        type: global_range
        random_range_angle: 360
        random_range_h: 0.7
        random_range_w: 0.4
        random_range_x: -0.2
        random_range_y: -0.35
      obj2: *id001
      background_0: &id002
        type: global_range
        random_range_angle: 360
        random_range_h: 20
        random_range_w: 20
        random_range_x: -10
        random_range_y: -10
      background_1: *id002
      background_2: *id002
      background_3: *id002
      background_4: *id002
      background_5: *id002
      background_6: *id002
      background_7: *id002
      background_8: *id002
  mode: manual
  num_episode: 1000000
  restart_per_success: 100
  object_config:
    background_0: &id003
      clip_range:
        max: 0.2
        min: 0.05
      filter_rule: []
      max_cached_num: 30
      is_not_rigid: true
      without_colliders: true
      path: object_usds/objaverse_usd_cooked
      type: load_object_from_path
    background_1: *id003
    background_2: *id003
    background_3: *id003
    background_4: *id003
    background_5: *id003
    background_6: *id003
    background_7: *id003
    background_8: *id003
    obj1_0:
      clip_range:
        max: 0.15
        min: 0.05
      filter_rule:
      - can_grasp
      max_cached_num: 30
      option:
      - adjust_thickness
      without_colliders: true
      path: object_usds/objaverse_usd_cooked
      type: load_object_from_path
    obj2:
      clip_range:
        max: 0.35
        min: 0.2
      filter_rule:
      - is_container
      max_cached_num: 30
      option:
      - force_top
      without_colliders: true
      path: object_usds/objaverse_usd_cooked
      type: load_object_from_path
  preprocess_config:
  - config:
      type: ccd
    type: ccd
  - config:
      config: default
      type: convexDecomposition
    type: collider
  robots:
  - type: manip/mobile_aloha/piper
  table_uid: aa49db8a801d402dac6cf1579536502c
  task_name: system1_scaling_14kobj_object_container_fgrandpos_bgrandpos_fgclip_NOrobotbaserandpos_bgcache10_bgclip_3L2obsAlign_refineActionSpace_aloha_precook
  usd_name: scene_usds/sim2real_scenes_align_for_scaling/base
evaluation_configs: []
