demonstration_configs:
- domain_randomization: &id001
    cameras:
      config_path: configs/cameras/fixed_camera_lift2_simbox.yml
      type: fixed
    random_environment:
      has_wall: false
      hdr: false
      robot_base_position: false
      robot_eepose: false
      table_texture: false
      table_type: false
      wall_texture: false
    rewrite_instruction: false
  generation_config: &id002
    action_path:
      mode: auto
      robot: 0
    articulation: []
    goal:
    - - obj1_uid:
        - '0'
        obj2_uid:
        - '6'
        position:
        - top
        fixed_position: true
        arm: auto
        grasp_idx: [0, 1, 2, 3, 4]
        force_fixed_grasp: true
        allow_fixed_grasp: true
        fixed_grasp_config:
          translation: [0.0, 0.06, 0.0]
        # gripper_rot_config:
        #   axis: x
        #   angle: 90
        fixed_position: true
        fixed_position_config:     # apply delta to the final object position to be placed
          - translation: [0, 0.04, 0]
            orientation: [1, 0, 0, 0]
        base_motion_list:
          0:
            - x: null
              y: [-0.05, 0.05]
              yaw: null
              type: align
          3:
            - x: -0.2
              y: 0.0
              yaw: 0.0
              type: delta
            - x: null
              y: [-0.05, 0.05]
              yaw: null
              type: align
            - x: 0.2
              y: 0.0
              yaw: 0.0
              type: delta
        motion_config:
          pre_grasp_distance: 0.08
          post_grasp_distance: 0.30
          pre_place_distance: 0.16
          post_place_distance: 0.08
    mode: manual
    planner: curobo
  instruction: Take out one of the three bowls and stack on the plate.    # update instruction
  layout_config: &id003
    type: random_custom_tableset
    in_order: true
    custom_tableset:
      # '0':
      #   type: centric_range
      #   skip_on_table_check: true
      #   angle_bilateral: true
      #   angle: 0
      #   w: 0.005
      #   h: 0.005
      #   buffer_size: 0.005
    - 0: &id090
        pos_x: 2.58301
        pos_y: -1.79701
        pos_z: -0.115
        additional_height: 0
        random_range_angle: 0
        orientation: [0.70710677, 0.70710677, 0.0 , 0.0 ]
        reset_orientation: true
        type: fixed_global_range
        skip_on_table_check: true
      1: &id092
        pos_x: 2.71502
        pos_y: -1.88971
        pos_z: -0.115
        additional_height: 0
        orientation: [0.70710677, 0.70710677, 0.0 , 0.0 ]
        reset_orientation: true
        random_range_angle: 0
        type: fixed_global_range
        skip_on_table_check: true
      2: &id093
        pos_x: 2.77327
        pos_y: -1.72668
        pos_z: -0.115
        additional_height: 0
        orientation: [0.70710677, 0.70710677, 0.0 , 0.0 ]
        reset_orientation: true
        random_range_angle: 0
        type: fixed_global_range
        skip_on_table_check: true
      6:
        type: centric_range
        angle_bilateral: true
        angle: 0
        w: 0.1
        h: 0.1
        buffer_size: 0.0
    - 0: *id092
      1: *id093
      2: *id090
      6:
        type: centric_range
        angle_bilateral: true
        angle: 0
        w: 0.1
        h: 0.1
        buffer_size: 0.0
  mode: manual
  num_episode: 400
  object_config: &id004
    # '0':
    #   type: existed_object
    #   uid_list:
    #   - 'a'
    #   - 'a_01'
    #   - 'a_02'
    '0':
      type: load_object_from_path
      filter_rule: []
      max_cached_num: 10
      path: "regex:^object_usds/custom_usd/ebench_usds/bowl/ready/.*\\.usd$"
      relative_scale: 0.6
      option:
      - plain_replace
      without_colliders: false
    '1':
      type: load_object_from_path
      filter_rule: []
      max_cached_num: 10
      path: "regex:^object_usds/custom_usd/ebench_usds/bowl/ready/.*\\.usd$"
      relative_scale: 0.6
      option:
      - plain_replace
      without_colliders: false
    '2':
      type: load_object_from_path
      filter_rule: []
      max_cached_num: 10
      path: "regex:^object_usds/custom_usd/ebench_usds/bowl/ready/.*\\.usd$"
      relative_scale: 0.6
      option:
      - plain_replace
      without_colliders: false
    '6':
      type: existed_object
      uid_list:
      - '_06'    
  preprocess_config:
  - &id005
    config:
      config: default
      type: convexDecomposition
    type: collider
  - type: rigid_body
  robots:
  - &id006
    type: manip/lift2/R5a
    position: [2.07, -1.35, -0.60]
    # position: [-0.88, 0.134, -0.432]  # update to fit the scene
    # orientation: [0, 0, 180]
  # update following
  table_uid: table
  task_name: ebench/mobile_manip/bowl_to_plate
  usd_name: scene_usds/ebench/simple_pnp/task10/scene
  env_vars:
    MDL_SYSTEM_PATH: "/isaac-sim/materials/:{ASSETS_DIR}/miscs/mdl/ebench/mdl:{ASSETS_DIR}/scene_usds/ebench/simple_pnp/task3/SubUSDs/materials"

evaluation_configs:
- domain_randomization: *id001
  num_test: 10
  num_steps: 1000
  robots:
  - *id006
  table_uid: table
  task_name: ebench/mobile_manip/bowl_to_plate_val_train_20p
  usd_name: scene_usds/ebench/simple_pnp/task10/scene
  env_vars:
    MDL_SYSTEM_PATH: "/isaac-sim/materials/:{ASSETS_DIR}/miscs/mdl/ebench/mdl:{ASSETS_DIR}/scene_usds/ebench/simple_pnp/task3/SubUSDs/materials"
