demonstration_configs:
- domain_randomization: &id007
    cameras:
      config_path: configs/cameras/fixed_camera_aloha_refined.yml
      type: fixed
    random_environment:
      has_wall: false
      hdr: false
      robot_base_position: false
      robot_eepose: false
      table_texture: false
      table_type: false
      wall_texture: false
    rewrite_instruction: false
  generation_config: &id008
    action_path:
      mode: auto
      robot: 0
    articulation: []
    reset_tcp: 0.2
    goal:
    - - - &id003
          obj1_uid:
          - object1
          obj2_uid:
          - container2
          position:
          - top
          fixed_position: true
          force_fixed_grasp: true
          allow_fixed_grasp: true
          arm: left
          mesh_top_only: true
          fixed_grasp_config: &id001
            translation:
            - 0.0
            - 0.0
            - -0.01
          fixed_position_config:
            translation:
            - 0.0
            - 0.07
            - 0.0
            orientation:
            - 1.0
            - 0.0
            - 0.0
            - 0.0
        - &id002
          obj1_uid:
          - object3
          obj2_uid:
          - container2
          position:
          - top
          fixed_position: true
          force_fixed_grasp: true
          allow_fixed_grasp: true
          arm: right
          mesh_top_only: true
          fixed_grasp_config: *id001
          fixed_position_config:
            translation:
            - 0.0
            - -0.07
            - 0.0
            orientation:
            - 1.0
            - 0.0
            - 0.0
            - 0.0
    - - - *id002
        - *id003
    mode: manual
    planner: curobo
  instruction: put the cups to the plates with relative color.
  layout_config: &id009
    ignored_objects: []
    custom_tableset:
      object1: &id004
        random_range_x: -0.05
        random_range_y: 0.2
        random_range_w: 0.2
        random_range_h: 0.3
        random_range_angle: 0
        additional_height: 0.01
        reset_orientation: true
        orientation:
        - 0.0
        - 1.0
        - 0.0
        - 0.0
        buffer_size: 0.05
        type: global_range
      object2: *id004
      object3: &id005
        random_range_x: -0.05
        random_range_y: -0.5
        random_range_w: 0.2
        random_range_h: 0.3
        random_range_angle: 0
        additional_height: 0.01
        reset_orientation: true
        orientation:
        - 0.0
        - 1.0
        - 0.0
        - 0.0
        buffer_size: 0.05
        type: global_range
      object4: *id005
    type: random_custom_tableset
  mode: manual
  num_episode: 500
  object_config: &id010
    object1: &id006
      type: load_object_from_path
      filter_rule: []
      max_cached_num: 10
      path: scene_usds/IROS_scenes_aloha_final/object_place1/clock
      fixed_scale: 0.0007
      option:
      - plain_replace
      without_colliders: true
    object2: *id006
    object3: *id006
    object4: *id006
    container2:
      type: existed_object
      uid_list:
      - 8c63e5e160064cd3862e4b5f8781032b
      without_colliders: true
      is_not_rigid: true
  preprocess_config: []
  robots:
  - &id011
    type: manip/mobile_aloha/piper
  table_uid: instance
  task_name: IROS_C_V5_Aloha/object_select1
  usd_name: scene_usds/IROS_scenes_aloha_final/object_place1/base
evaluation_configs:
- domain_randomization: *id007
  generation_config: *id008
  instruction: put the cups to the plates with relative color.
  layout_config: *id009
  mode: manual
  num_test: 20
  object_config: *id010
  preprocess_config: []
  robots:
  - *id011
  table_uid: instance
  task_name: IROS_C_V5_Aloha_seen_renamed/collect_two_alarm_clocks
  usd_name: scene_usds/IROS_scenes_aloha_final/object_place1/base
- domain_randomization: *id007
  generation_config: *id008
  instruction: put the cups to the plates with relative color.
  layout_config: *id009
  mode: manual
  num_test: 20
  object_config: *id010
  preprocess_config: []
  robots:
  - *id011
  table_uid: instance
  task_name: IROS_C_V5_Aloha_unseen_renamed/collect_two_alarm_clocks
  usd_name: scene_usds/IROS_scenes_aloha_final/object_place1/base
