evaluation_configs:
  - task_name: ebench/labutopia_lab_poc/lift2_candidate/level1_pick
    instruction: Pick up the conical bottle from the table.
    usd_name: scene_usds/labutopia/level1_poc/lab_001/scene
    table_uid: table
    mode: manual
    num_test: 1
    num_steps: 800
    physics_dt: 0.0166666667
    rendering_dt: 0.0166666667
    robots:
      - type: manip/lift2/R5a
        position: [0.0, 0.0, 0.0]
    domain_randomization:
      cameras:
        config_path: configs/cameras/fixed_camera_lift2_simbox.yml
        type: fixed
      random_environment:
        has_wall: false
        hdr: false
        robot_base_position: false
        robot_eepose: false
        table_texture: false
        table_type: false
        wall_texture: false
      rewrite_instruction: false
    generation_config:
      action_path:
        mode: manual
        robot: 0
      articulation: []
      goal:
        - - - type: manip/labutopia/object_height_delta
              obj_uid: obj_conical_bottle02
              axis: z
              min_delta: 0.10
              skip_steps: 1
              succ_cnts: 59
      mode: manual
      planner: curobo
    object_config: {}
    preprocess_config: []
    layout_config:
      ignored_objects: []
      type: null
    env_vars:
      MDL_SYSTEM_PATH: "/isaac-sim/materials/:{ASSETS_DIR}/scene_usds/labutopia/level1_poc/lab_001/SubUSDs/materials:{ASSETS_DIR}/miscs/mdl/labutopia/mdl"
