camera1:
  clipping_range_max: 10000.0
  clipping_range_min: 0.001
  exists: false
  focal_length: 5.0
  frequency: 60
  horizontal_aperture: 10.0
  name: camera1
  orientation:
  - -0.0071865058262247095
  - -0.5792785229595211
  - -0.005107428795172445
  - 0.815081996576386
  position:
  - 0.28070902824401855
  - -0.02326910011470318
  - 1.6857764720916748
  prim_path: /camera1
  resolution:
  - 1280
  - 720
  vertical_aperture: 5.625
  with_distance: true
  with_semantic: false
  with_bbox2d: false
  with_bbox3d: false
  with_motion_vector: false
obs_camera:
  clipping_range_max: 10000.0
  clipping_range_min: 0.01
  exists: false
  focal_length: 4.5
  frequency: 60
  horizontal_aperture: 6.4
  name: obs_camera
  orientation:
  - 0.0
  - -0.42261829
  - 0.0
  - 0.90630777
  position:
  - 0.65
  - 0.0
  - 1.85
  prim_path: /obs_camera
  resolution:
  - 640
  - 480
  vertical_aperture: 4.8
  with_distance: true
  with_semantic: false
  with_bbox2d: false
  with_bbox3d: false
  with_motion_vector: false
