camera1:
  name: camera_1
  exists: false
  prim_path: /LabUtopiaOpenDoorCamera1
  position: [2.0, 0.0, 2.0]
  orientation: [0.61237, 0.35355, 0.35355, 0.61237]
  camera_axes: usd
  resolution: [256, 256]
  image_type: rgb
  with_distance: false
  with_semantic: false
  with_bbox2d: false
  with_bbox3d: false
  with_motion_vector: false
camera2:
  name: camera_2
  exists: false
  prim_path: /LabUtopiaOpenDoorCamera2
  position: [0.75, -0.56, 1.02]
  orientation: [0.87184, 0.4898, 0.0, 0.0]
  camera_axes: usd
  resolution: [512, 512]
  focal_length: 5.0
  horizontal_aperture: 10.0
  image_type: rgb
  task_view: level1_open_door
  with_distance: false
  with_semantic: false
  with_bbox2d: false
  with_bbox3d: false
  with_motion_vector: false
