camera1:
  name: camera_1
  exists: false
  prim_path: /LabUtopiaCamera1
  position: [2.0, 0.0, 2.0]
  orientation: [0.61237, 0.35355, 0.35355, 0.61237]
  camera_axes: usd
  resolution: [256, 256]
  image_type: rgb
  with_distance: false
  with_semantic: false
  with_bbox2d: false
  with_bbox3d: false
  with_motion_vector: false
camera2:
  name: camera_2
  exists: false
  prim_path: /LabUtopiaCamera2
  position: [9.6, 0.0, 2.5]
  orientation: [0.70711, 0.0, 0.0, -0.70711]
  camera_axes: usd
  resolution: [256, 256]
  image_type: rgb
  with_distance: false
  with_semantic: false
  with_bbox2d: false
  with_bbox3d: false
  with_motion_vector: false
