demonstration_configs:
- domain_randomization: &id003
    cameras:
      config_path: configs/cameras/fixed_camera_robotiq_s2r_3L_align_twoObs.yml
      type: fixed
    random_environment:
      has_wall: false
      hdr: false
      robot_base_position: false
      robot_eepose: false
      table_texture: false
      table_type: false
      wall_texture: false
    rewrite_instruction: false
  generation_config: &id004
    action_path:
      mode: auto
      robot: 0
    articulation: []
    goal:
    - - - obj1_uid:
          - brush
          obj2_uid:
          - paint1
          position:
          - top
          fixed_position: true
          force_fixed_grasp: true
          fixed_grasp_config: &id001
            translation:
            - 0.0
            - 0.01
            - -0.01
            orientation:
            - 0.0
            - 1.0
            - 0.0
            - 0.0
          allow_fixed_grasp: true
    - - - obj1_uid:
          - brush
          obj2_uid:
          - paint2
          position:
          - top
          fixed_position: true
          force_fixed_grasp: true
          fixed_grasp_config: *id001
          allow_fixed_grasp: true
    - - - obj1_uid:
          - brush
          obj2_uid:
          - paint3
          position:
          - top
          fixed_position: true
          force_fixed_grasp: true
          fixed_grasp_config: *id001
          allow_fixed_grasp: true
    mode: manual
    planner: curobo
  instruction: put the box in the basket.
  layout_config:
    ignored_objects: []
    custom_tableset:
      brush:
        w: 0.1
        h: 0.1
        angle: 0
        angle_bilateral: false
        type: centric_range
      paint1: &id005
        pos_x: 0.14497
        pos_y: -0.24906
        additional_height: 0.01
        random_range_angle: 0
        reset_orientation: true
        orientation:
        - 0.5
        - 0.5
        - -0.5
        - -0.5
        type: fixed_global_range
      paint2: &id006
        pos_x: 0.14626
        pos_y: 0.03432
        additional_height: 0.01
        random_range_angle: 0
        reset_orientation: true
        orientation:
        - 0.5
        - 0.5
        - -0.5
        - -0.5
        type: fixed_global_range
      paint3: &id007
        pos_x: 0.12698
        pos_y: 0.29414
        additional_height: 0.01
        random_range_angle: 0
        reset_orientation: true
        orientation:
        - 0.5
        - 0.5
        - -0.5
        - -0.5
        type: fixed_global_range
    type: random_custom_tableset
  mode: manual
  num_episode: 500
  object_config: &id008
    brush:
      type: existed_object
      uid_list:
      - brush_pen
      without_colliders: true
      is_not_rigid: true
    paint1: &id002
      type: load_object_from_path
      filter_rule: []
      max_cached_num: 20
      path: scene_usds/IROS_scenes_final/scene_paint/paints
      fixed_scale: 1.0
      option:
      - plain_replace
      without_colliders: true
      is_not_rigid: true
    paint2: *id002
    paint3: *id002
  preprocess_config: []
  robots:
  - &id009
    config:
      gripper_type: robotiq
    default_joint_positions:
    - 0.0
    - -0.785
    - 0.0
    - -2.356
    - 0.0
    - 1.57079
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    type: franka
  table_uid: instance_01
  task_name: IROS_C_V4_RoboTiq/brush_paint
  usd_name: scene_usds/IROS_scenes_final/scene_paint/base
evaluation_configs:
- domain_randomization: *id003
  generation_config: *id004
  instruction: put the box in the basket.
  layout_config: &id010
    ignored_objects: []
    custom_tableset:
      paint1: *id005
      paint2: *id006
      paint3: *id007
    type: random_custom_tableset
  mode: manual
  num_test: 20
  object_config: *id008
  preprocess_config: []
  robots:
  - *id009
  table_uid: instance_01
  task_name: IROS_C_V4_RoboTiq_seen/brush_paint
  usd_name: scene_usds/IROS_scenes_final/scene_paint/base
- domain_randomization: *id003
  generation_config: *id004
  instruction: put the box in the basket.
  layout_config: *id010
  mode: manual
  num_test: 20
  object_config: *id008
  preprocess_config: []
  robots:
  - *id009
  table_uid: instance_01
  task_name: IROS_C_V4_RoboTiq_unseen/brush_paint
  usd_name: scene_usds/IROS_scenes_final/scene_paint/base
