demonstration_configs:
- domain_randomization: &id005
    cameras:
      config_path: configs/cameras/fixed_camera_robotiq_s2r_3L_align_twoObs.yml
      type: fixed
    random_environment:
      has_wall: false
      hdr: false
      robot_base_position: false
      robot_eepose: false
      table_texture: false
      table_type: false
      wall_texture: false
    rewrite_instruction: false
  generation_config: &id006
    action_path:
      mode: auto
      robot: 0
    articulation: []
    goal:
    - - obj1_uid:
        - cup2
        obj2_uid:
        - plate2
        position:
        - top
        fixed_position: true
        force_fixed_grasp: true
        allow_fixed_grasp: true
      - obj1_uid:
        - cup1
        obj2_uid:
        - plate1
        position:
        - top
        fixed_position: true
        force_fixed_grasp: true
        allow_fixed_grasp: true
    mode: manual
    planner: curobo
  instruction: put the cups to the plates with relative color.
  layout_config:
    ignored_objects: []
    in_order: true
    custom_tableset:
      plate1: &id001
        random_range_x: -0.15
        random_range_y: -0.2
        random_range_w: 0.4
        random_range_h: 0.55
        random_range_angle: 0
        additional_height: 0.01
        reset_orientation: true
        orientation:
        - 0.0
        - 0.0
        - 0.70711
        - 0.70711
        type: global_range
      plate2: *id001
      cup1: &id002
        random_range_x: -0.15
        random_range_y: -0.2
        random_range_w: 0.3
        random_range_h: 0.55
        random_range_angle: 0
        additional_height: 0.01
        buffer_size: 0.05
        reset_orientation: true
        orientation:
        - 0.0
        - 0.0
        - 0.70711
        - 0.70711
        type: global_range
      cup2: *id002
    type: random_custom_tableset
  mode: manual
  num_episode: 500
  object_config: &id007
    cup1: &id003
      type: load_object_from_path
      filter_rule: []
      max_cached_num: 10
      path: scene_usds/IROS_scenes_final/scene_cup/cups
      fixed_scale: 0.0003
      option:
      - plain_replace
      - cup_plate_replace
      without_colliders: true
    plate1: &id004
      type: load_object_from_path
      filter_rule: []
      max_cached_num: 10
      path: scene_usds/IROS_scenes_final/scene_cup/plates
      fixed_scale: 0.0005
      option:
      - plain_replace
      - cup_plate_replace
      without_colliders: true
      is_not_rigid: true
    cup2: *id003
    plate2: *id004
    book1:
      type: existed_object
      uid_list:
      - daf860020fdf4ed392f07933977ee89b
      is_not_rigid: true
    book2:
      type: existed_object
      uid_list:
      - c594cb43f36140c8a422b069d6d9714d
      is_not_rigid: true
    book3:
      type: existed_object
      uid_list:
      - 49d47c6c27648a6af26d6c912c03826
      is_not_rigid: true
    book4:
      type: existed_object
      uid_list:
      - 97e7c7f61104b6785c3bd0fdb99c74d
      is_not_rigid: true
    plant:
      type: existed_object
      uid_list:
      - 2704c1bafd44bfd9e98538276ad5614
      is_not_rigid: true
    radio:
      type: existed_object
      uid_list:
      - f79ee359a23478ab9d2cc0d0da3fc39
      is_not_rigid: true
    keyboard:
      type: existed_object
      uid_list:
      - f0a9fc8b51004680904f320e7133e951
      is_not_rigid: true
    pen:
      type: existed_object
      uid_list:
      - b6c09ed6acaa45ebb20c53696372ce3a
      is_not_rigid: true
  preprocess_config: []
  robots:
  - &id008
    config:
      gripper_type: robotiq
    type: franka
    default_joint_positions:
    - 0.0
    - -0.785
    - 0.0
    - -2.356
    - 0.0
    - 1.57079
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
  table_uid: instance
  task_name: IROS_C_V4_RoboTiq/colorful_cups
  usd_name: scene_usds/IROS_scenes_final/scene_cup/base_2
evaluation_configs:
- domain_randomization: *id005
  generation_config: *id006
  instruction: put the cups to the plates with relative color.
  layout_config: &id009
    ignored_objects: []
    custom_tableset:
      cup1:
        random_range_x: -0.15
        random_range_y: 0.0
        random_range_w: -0.1
        random_range_h: -0.1
        random_range_angle: 0
        additional_height: 0.01
        reset_orientation: true
        orientation:
        - 0.0
        - 0.0
        - 0.70711
        - 0.70711
        type: fixed_random_global_range
      cup2:
        random_range_x: -0.1
        random_range_y: 0.25
        random_range_w: -0.1
        random_range_h: 0.1
        random_range_angle: 0
        additional_height: 0.01
        reset_orientation: true
        orientation:
        - 0.0
        - 0.0
        - 0.70711
        - 0.70711
        type: fixed_random_global_range
      plate1:
        random_range_x: 0.06957
        random_range_y: 0.0
        random_range_w: -0.1
        random_range_h: -0.1
        random_range_angle: 0
        additional_height: 0.01
        reset_orientation: true
        orientation:
        - 0.0
        - 0.0
        - 0.70711
        - 0.70711
        type: fixed_random_global_range
      plate2:
        random_range_x: 0.105
        random_range_y: 0.25
        random_range_w: 0.1
        random_range_h: -0.1
        random_range_angle: 0
        additional_height: 0.01
        reset_orientation: true
        orientation:
        - 0.0
        - 0.0
        - 0.70711
        - 0.70711
        type: fixed_random_global_range
    type: random_custom_tableset
  mode: manual
  num_test: 10
  object_config: *id007
  preprocess_config: []
  robots:
  - *id008
  table_uid: instance
  task_name: IROS_C_V4_RoboTiq_seen/colorful_cups
  usd_name: scene_usds/IROS_scenes_final/scene_cup/base_2
- domain_randomization: *id005
  generation_config: *id006
  instruction: put the cups to the plates with relative color.
  layout_config: *id009
  mode: manual
  num_test: 20
  object_config: *id007
  preprocess_config: []
  robots:
  - *id008
  table_uid: instance
  task_name: IROS_C_V4_RoboTiq_seen/colorful_cups
  usd_name: scene_usds/IROS_scenes_final/scene_cup/base_2
- domain_randomization: *id005
  generation_config: *id006
  instruction: put the cups to the plates with relative color.
  layout_config: *id009
  mode: manual
  num_test: 10
  object_config: *id007
  preprocess_config: []
  robots:
  - *id008
  table_uid: instance
  task_name: IROS_C_V4_RoboTiq_unseen/colorful_cups
  usd_name: scene_usds/IROS_scenes_final/scene_cup/base_2
- domain_randomization: *id005
  generation_config: *id006
  instruction: put the cups to the plates with relative color.
  layout_config: *id009
  mode: manual
  num_test: 20
  object_config: *id007
  preprocess_config: []
  robots:
  - *id008
  table_uid: instance
  task_name: IROS_C_V4_RoboTiq_unseen/colorful_cups
  usd_name: scene_usds/IROS_scenes_final/scene_cup/base_2
