demonstration_configs:
- domain_randomization: &id006
    cameras:
      config_path: configs/cameras/fixed_camera_robotiq_s2r_3L_align_twoObs.yml
      type: fixed
    random_environment:
      has_wall: false
      hdr: false
      robot_base_position: false
      robot_eepose: false
      table_texture: false
      table_type: false
      wall_texture: false
    rewrite_instruction: false
  generation_config: &id007
    action_path:
      mode: auto
      robot: 0
    articulation: []
    goal:
    - - &id001
        obj1_uid:
        - battery1
        obj2_uid:
        - badbin
        position:
        - top
        fixed_position: true
        force_fixed_grasp: true
        allow_fixed_grasp: true
        mesh_top_only: true
      - &id003
        obj1_uid:
        - can1
        obj2_uid:
        - goodbin
        position:
        - top
        fixed_position: true
        force_fixed_grasp: true
        allow_fixed_grasp: true
        mesh_top_only: true
      - &id002
        obj1_uid:
        - battery2
        obj2_uid:
        - badbin
        position:
        - top
        fixed_position: true
        force_fixed_grasp: true
        allow_fixed_grasp: true
        mesh_top_only: true
    - - *id001
      - *id002
      - *id003
    - - *id003
      - *id001
      - *id002
    mode: manual
    planner: curobo
  instruction: put the box in the basket.
  layout_config: &id008
    ignored_objects: []
    custom_tableset:
      battery1: &id004
        random_range_x: -0.2
        random_range_y: -0.2
        random_range_w: 0.4
        random_range_h: 0.2
        random_range_angle: 360
        additional_height: 0.01
        reset_orientation: true
        buffer_size: 0.05
        type: global_range
      battery2: *id004
      can1:
        random_range_x: -0.2
        random_range_y: -0.2
        random_range_w: 0.4
        random_range_h: 0.2
        random_range_angle: 360
        additional_height: 0.01
        reset_orientation: true
        orientation:
        - 0.0
        - 1.0
        - 0.0
        - 0.0
        buffer_size: 0.05
        type: global_range
    type: random_custom_tableset
  mode: manual
  num_episode: 500
  object_config: &id009
    goodbin:
      type: existed_object
      uid_list:
      - goodbin
    badbin:
      type: existed_object
      uid_list:
      - badbin
    can1:
      type: load_object_from_path
      filter_rule: []
      max_cached_num: 20
      path: scene_usds/IROS_scenes_final/scene_waste/cans
      fixed_scale: 0.0006
      option:
      - plain_replace
      without_colliders: true
    battery1: &id005
      type: load_object_from_path
      filter_rule: []
      max_cached_num: 20
      path: scene_usds/IROS_scenes_final/scene_waste/batteries
      fixed_scale: 2.5
      option:
      - plain_replace
      without_colliders: true
    battery2: *id005
  preprocess_config:
  - &id010
    type: apply_default_physics_material
  robots:
  - &id011
    config:
      gripper_type: robotiq
    default_joint_positions:
    - 0.0
    - -0.785
    - 0.0
    - -2.356
    - 0.0
    - 1.57079
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    type: franka
  table_uid: instance
  task_name: IROS_C_V4_RoboTiq/waste_split
  usd_name: scene_usds/IROS_scenes_final/scene_waste/base
evaluation_configs:
- domain_randomization: *id006
  generation_config: *id007
  instruction: put the box in the basket.
  layout_config: *id008
  mode: manual
  num_test: 20
  object_config: *id009
  preprocess_config:
  - *id010
  robots:
  - *id011
  table_uid: instance
  task_name: IROS_C_V4_RoboTiq_seen/waste_split
  usd_name: scene_usds/IROS_scenes_final/scene_waste/base
- domain_randomization: *id006
  generation_config: *id007
  instruction: put the box in the basket.
  layout_config: *id008
  mode: manual
  num_test: 20
  object_config: *id009
  preprocess_config:
  - *id010
  robots:
  - *id011
  table_uid: instance
  task_name: IROS_C_V4_RoboTiq_unseen/waste_split
  usd_name: scene_usds/IROS_scenes_final/scene_waste/base
